"""Cluster 4 regression tests: B01 DOCX export.

The other cluster-4 backlog items (B02 preview, B03/B04 modal, B05 alert email,
B06 alert push, B07 quota what-if) were already shipped at HEAD `3440ee0` —
their implementation files exist and are wired. This test pins B01 (DOCX) so
the feature can't silently regress.
"""

from __future__ import annotations

import io
import zipfile

import pytest


@pytest.mark.regression
def test_b01_docx_export_produces_valid_word_file() -> None:
    """B01: `_generate_document_docx` must produce a valid .docx (Open XML) file.

    The original brief said document.py generated plain text only. This test
    proves the DOCX path exists, returns a non-empty Office Open XML zip
    (PK signature), and the body contains the title + a heading + body text
    we passed in.
    """
    from hr_advisory.api.routers.document import _generate_document_docx

    content = "\n".join(
        [
            "1. KEY EMPLOYMENT TERMS",
            "",
            "The Employee shall serve as Software Engineer.",
            "",
            "2. COMPENSATION",
            "",
            "- Monthly salary: SGD 5,000",
            "",
            "SECTION A: ACKNOWLEDGEMENT",
            "",
            "________________________",
            "Employee Signature",
        ]
    )

    docx_bytes = _generate_document_docx(
        title="Employment Contract",
        content=content,
        company_name="Acme Pte Ltd",
    )

    assert docx_bytes, "DOCX bytes must not be empty"
    assert docx_bytes[:2] == b"PK", (
        ".docx files are zip archives — must start with the PK signature"
    )
    assert len(docx_bytes) > 2000, "Generated DOCX is suspiciously small"

    # Verify it's a parseable Office Open XML document and the body +
    # footer parts contain the strings we wrote.
    with zipfile.ZipFile(io.BytesIO(docx_bytes)) as zf:
        names = zf.namelist()
        assert "word/document.xml" in names, (
            "Generated archive is not a valid .docx (missing word/document.xml)"
        )
        body_xml = zf.read("word/document.xml").decode("utf-8")
        # python-docx writes footers to word/footer*.xml — pull them all.
        footer_xml = "".join(
            zf.read(name).decode("utf-8") for name in names if name.startswith("word/footer")
        )

    assert "Acme Pte Ltd" in body_xml
    assert "Employment Contract" in body_xml
    assert "KEY EMPLOYMENT TERMS" in body_xml
    assert "Software Engineer" in body_xml
    assert "Generated by Arbor HR Platform" in footer_xml


@pytest.mark.regression
def test_b01_download_endpoint_accepts_docx_format() -> None:
    """B01: `download_document` route must accept format='docx'.

    Inspect the function signature and error path to confirm 'docx' is in
    the allowed format set, alongside 'pdf' and 'txt'.
    """
    import inspect

    from hr_advisory.api.routers import document as doc_router

    source = inspect.getsource(doc_router.download_document)
    assert '"docx"' in source, "download_document must list 'docx' as a supported format"
    assert '"pdf"' in source
    assert '"txt"' in source
    # Pin the explicit allow-list
    assert 'format not in ("pdf", "docx", "txt")' in source, (
        "download_document must validate format against {pdf, docx, txt}"
    )
