export { ShadowWidget } from "./ShadowWidget";
export { CommandSurface } from "./CommandSurface";
export { ShadowAgentProvider, useShadowAgent } from "./ShadowAgentContext";
export type { CalculatorDisplayResult } from "./ShadowAgentContext";
export { classifyIntent } from "./action-registry";
export type { ActionType, ClassifiedIntent } from "./action-registry";
export { ShadowMargin } from "./ShadowMargin";
export type { ShadowInsight } from "./ShadowMargin";
export { InlineAnnotation } from "./InlineAnnotation";
export type { AnnotationData } from "./InlineAnnotation";
export { ShadowBriefingCard } from "./ShadowBriefingCard";
export { useShadowContext } from "./useShadowContext";
export { useObservation } from "./useObservation";
export type { PageVisit, ObservationInsight } from "./useObservation";
